---
- name: Gather EC2 facts
  ec2_remote_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "cloudforms"
  register: ec2_facts

- name: Delete elastic IP
  ec2_eip:
    ip: "{{item.public_ip_address}}"
    region: "{{region}}"
    state: absent
  with_items: "{{ ec2_facts.instances }}"
  when: item.state != 'terminated'

- name: Terminate EC2 VMs
  ec2:
    state: absent
    region: "{{ region }}"
    instance_ids: "{{ item.id }}"
    wait: yes
  with_items: "{{ ec2_facts.instances }}"
  when: item.state != 'terminated'  