---
# Adds a set of test users to OpenShift
# ansible-playbook -i inventory/inventory.cfg -e password=something
- name: Add Users to OpenShift
  hosts: ocplab
  remote_user: ec2-user

  tasks:
    # htpasswd module requires passlib, just call httppasswd directlt
    - name: Add demo users
      command: "htpasswd -b {{htpasswd_path}} {{item}} {{password}}"
      become: true
      with_items:
        - "admin"
        - "developer1"
        - "developer2"
        - "developer3"
        - "developer4"
        - "developer5"
        - "nexus"
  
    - name: Cluster admin rights
      command: "oadm policy add-cluster-role-to-user cluster-admin admin"
