kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: "nexus-pv"
  annotations:
    volume.alpha.kubernetes.io/storage-class: "standard" 
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"