---
- name: Create nexus project
  command: "oc new-project --display-name=Nexus nexus"

- name: Provision nexus template
  command: "oc create -f roles/setup-nexus-aws/files/persistent-nexus-template.yml"

- name: Create nexus application
  command: "oc new-app nexus2-persistent -p SERVICE_NAME=nexus"

- name: Output MAVEN_MIRROR_URL
  debug:
    msg: "Use this URL in OpenShift for MAVEN_MIRROR_URL 'http://nexus.nexus:8081/content/groups/public'"