---
- name: Check parameters
  fail: msg="Variable '{{ item }}' is not defined or is empty"
  when: (item not in vars) or vars[item] == ''
  with_items: 
    - az

- name: Create storage class file
  template:
    src: "../files/storage-class.yml"
    dest: "/tmp/storage-class.yml"

- name: Create storage class
  command: "oc create -f /tmp/storage-class.yml"